FROM golang:1.21.3-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN chmod +x ./cmd/config.sh

ARG PORT
ARG WEB_URL
ARG GOOGLE_API_KEY
ARG SPOTIFY_CLIENT_ID
ARG SPOTIFY_CLIENT_SECRET
ARG SPOTIFY_STATE
ARG SPOTIFY_REDIRECT_URI
ARG RAPID_API_KEY

RUN sh cmd/config.sh ${PORT} ${WEB_URL} ${GOOGLE_API_KEY} ${SPOTIFY_CLIENT_ID} $SPOTIFY_CLIENT_SECRET ${SPOTIFY_STATE} ${SPOTIFY_REDIRECT_URI} ${RAPID_API_KEY}

RUN go build -o api cmd/api.go

CMD [ "./api" ]