server:
  port: 8080
  webUrl: 'http://localhost:3000/auth'

google:
  apiKey: ''

spotify:
  clientId: ''
  clientSecret: ''
  state: ''
  redirectUri: 'http://localhost:8080/oauth/callback'

rapidApi:
  apiKey: ''
